### ISSUE TITLE
Lua port

### ISSUE THREAD

**Issue by ravener** [hunar4321/particle-life#60]
I ported the basic example from the README into Lua using [LÖVE](https://love2d.org)

https://github.com/ravener/love-life

**Comment by hunar4321** [comment]
Great Job and very nice capture of the fly :)

**Comment by hunar4321** [comment]
I have added this link to the "Other Ports" section in readme so that people with Lua background benefit from your implementation. 
Best

**Comment by hunar4321** [comment]
> I ported the basic example from the README into Lua using [LÖVE](https://love2d.org)
> 
> https://github.com/ravener/love-life

By the way, I just had a look at your GitHub profile and read that you are from Afghanistan and you are programming on an Android phone because you don't have a Computer!
You are truly amazing and inspirational. 
Keep up the good work

**Comment by ravener** [comment]
@hunar4321 Thanks! Will try my best.
