### ISSUE TITLE
Question: is this based on rule-set ?

### ISSUE THREAD

**Issue by imvetri** [hunar4321/particle-life#66]

**Comment by Cervantes21** [comment]
You can be more specific?

**Comment by imvetri** [comment]
How does particle-life simulator work ?

My assumption is that there is a rule runner running rules that renders the view.

**Comment by dangarfield** [comment]
Yes. Look at the video for a full description:
https://youtu.be/0Kx4Y9TVMGg
The code is also very readable and clear
