### ISSUE TITLE
release binary version doesn't seems to use openMP

### ISSUE THREAD

**Issue by ker2x** [hunar4321/particle-life#68]
Hi there, thank you for your awesome code.

the binary release I downloaded seems to have the same performance of my compiled code with openMP **disabled**. So I assume that openMP is indeed disabled.

(without openMP: 17fps. with openMP: 50fps)

I don't think there is any drawback in enabling it in the release binary

**Comment by hunar4321** [comment]
@ker2x Thanks. I have accepted the pull request.
